### ISSUE TITLE
🐛 [Bug] option from select input is not dynamic

### ISSUE THREAD

**Issue by ogerly** [Human-Connection/Human-Connection#1035]
## :bug: Bugreport
there is a problem with the select option fields. 
these don't change dynamically when I change the language.
only when you reload the page (hard) then the change is there.
the select

![ezgif com-video-to-gif (4)](https://user-images.githubusercontent.com/1324583/61103457-5d4c0180-a472-11e9-84fa-1cc5c87fc183.gif)

### Steps to reproduce the behavior
1. go to the homepage
2. have a look at the select field to sort contributions
3. change language to english <> german
4. the select field does not change the language.

### Expected behavior
 
the options of a select field should be changed dynamically when changing the language. reloading the page is absolutely impossible and no alternative is available

**Comment by mattwr18** [comment]
we talked about this issue, and have decided not to do this before the release.
@roschaefer was suggesting that we would need to make a change to the styleguide to make the label reactive, so that it would change the label when the user changes the locale.
@alina-beck would you know how to update the styleguide to achieve this? again, after the release

**Comment by alina-beck** [comment]
I have an idea... I've assigned myself to the issue and will try to fix it after the release!

**Comment by alina-beck** [comment]
This issue is no longer reproducible on production.
