### ISSUE TITLE
💬 [Question] Put the Language Menu in the Users Menu if possible

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#1207]
## :speech_balloon: Question

Should we put the language menu into the user menu, if possible?
Asked Dennis and suggested it.

Yeah, may be, answered the DEVs.
If it’s not possible, because there is no user menu, just leave it in the header, but now at the position of the user menu …

<img width="1812" alt="Bildschirmfoto 2019-08-07 um 12 15 26" src="https://user-images.githubusercontent.com/25344101/62615400-75962b80-b90d-11e9-9f62-1ab8127a22bf.png">

**Comment by DennisHack** [comment]
Frage noch dazu: Wie kompliziert ist es, die Sprachauswahl bei eingeloggtem Zustand auszublenden?
 Mögliche Lösung?
How difficult is it to hide language button, when user is logged in? Possible solution?

**Comment by ogerly** [comment]
for guests, the language selection should always be displayed. 
in the registered state, the user should have a "default language" point in his profile settings where a fixed language is defined. 
otherwise i would put a dot in the filter where you can choose the language of the contributions. 
a user who has set his default language for the system will always keep it. 
but the languages of the contributions .. have nothing to do with the language setting.

____
für gäste sollte immer die sprachauswahl angezeigt werden. 

im angemeldeten zustand sollte der user in seinen einstellungen im profil einen punkt haben "default language" wo eine feste sprache definiert wird. 
ansonsten würde ich einen punkt im filter mit unterbringen wo man die sprache der beiträge auswählen kann. 
ein user der einmal seine default sprache für das system eingestellt hat behält diese auch meist immer. 
aber die sprachen der beiträge .. haben mit der spracheinstellung nichts zu tun.

**Comment by Tirokk** [comment]
@DennisHack and @datenbrei have to decide if this is still desirable.
