### ISSUE TITLE
🐛 [Bug] Scroll position is wrong when navigating back to index from a post

### ISSUE THREAD

**Issue by alina-beck** [Human-Connection/Human-Connection#1471]
## :bug: Bugreport
reported by @ulfgebhardt 

When I scroll down the index page, load more posts, click on one of the posts, then click the back button in the browser my scroll position is somewhere _above_ the `load more` threshold and I have to scroll down and load posts again to get back to where I was.

### Steps to reproduce the behavior
1. go to index page
2. scroll down beyond `load more`
3. wait for more posts to load
4. click one of the posts
5. click `back` button in the browser
6. be confused – because the post you just clicked is gone and you need to scroll down and load it again

### Expected behavior
When I navigate back to index from a post I want to land where I left (i.e. at the position of the post I just had open).

**Comment by mattwr18** [comment]
this seems to not be an issue in `dev` mode
![Screenshot from 2019-10-11 16-42-56](https://user-images.githubusercontent.com/26943915/66660828-32767280-ec46-11e9-912c-6b73c5d2c177.png)

Actually, checking on `nitro-staging` and `alpha`, I couldn't replicate... though I have noticed this on my mobile... maybe this bug was fixed for desktop by @roschaefer refactor of the `scrollBehavior`, but still an issue for mobile, or it was first reported from mobile??

**Comment by alina-beck** [comment]
@mattwr18 not sure – it was one of the issues @ulfgebhardt reported a while ago... back then I could replicate it in `dev` mode on desktop. so yeah, if it works for you now maybe it has been fixed!? either by the `scrollBehavior` refactoring or something we did with the `pagination`?
