### ISSUE TITLE
🐛 [Bug] Links in Comments don't show up

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#1661]
## :bug: Bugreport

If a link is inserted in an Comment, it does not get displayed.

The Editor:
![link-ok](https://user-images.githubusercontent.com/13457963/65338189-f2354e80-dbc9-11e9-85fa-db5a629d11ea.png)

The comment when saved:
![link-not-ok](https://user-images.githubusercontent.com/13457963/65338213-00836a80-dbca-11e9-83a9-7a56babd22e1.png)

### Steps to reproduce the behavior
1. Insert a link in a comment
2. save

### Expected behavior

When writing comments it shoould be in one of two ways:

- Ether you should be able to insert links and they can be shown
- or you should not be able to insert links at all

### Version & Environment
 Type: [Desktop]      
 - OS: [Linux]      
 - Browser: [Firefox] 
 - Version [69]  
 - Device: [Notebook]  

### Additional context

Now, that we can disable comments as a moderator I think it would be ok to allow links.

**Comment by datenbrei** [comment]
If the comment ends with an empty line it seems to have no problems.

**Comment by mattwr18** [comment]
closed by a number of different `PR`s the latest being https://github.com/Human-Connection/Human-Connection/pull/1678

**Comment by erhardtstiefel** [comment]
This is a test link https://erhardt-stiefel.de/index.php/2019/09/21/programmieren-lernen-neugierig/

**Comment by mattwr18** [comment]
hey @erhardtstiefel this link shows up in a comment if the comment itself is not greater than 180 characters, otherwise it can be truncated and only showed when the `show more` link is clicked
![Screenshot from 2019-10-08 09-45-57](https://user-images.githubusercontent.com/26943915/66376793-ad266000-e9b0-11e9-9499-b00952646d5e.png)
![Screenshot from 2019-10-08 09-47-20](https://user-images.githubusercontent.com/26943915/66376804-b1527d80-e9b0-11e9-8378-24da25956291.png)
![Screenshot from 2019-10-08 09-47-32](https://user-images.githubusercontent.com/26943915/66376813-b3b4d780-e9b0-11e9-89fd-a48d319c504c.png)

**Comment by erhardtstiefel** [comment]
I guess it works fine in any case
