### ISSUE TITLE
🐛 [Bug] Follower/Following Lists are not expandable

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#1741]
## :bug: Bugreport
If somebody has a lot of followers or is following more people, just a few of them is shown in the profile. There is no way to expand the list with a click or to open a new window where all followers are shown.
![contacts-do-not-expand](https://user-images.githubusercontent.com/13457963/65749389-467a8a00-e106-11e9-9de5-7f3ad5bc4a67.png)

### Steps to reproduce the behavior
1. Go into your profile
2. See the followers on the left
3. have no chance to see all followers

### Expected behavior
I would espect to click below the list and have the list expanded in place. Another solution could be to let it contain every follower from scratch, but the first approach may be better.

### Version & Environment
 Type: [Desktop]      
 - OS: [Linux|Windows]      
 - Browser: [Firefox] 
 - Version [69]  
 - Device: [Notebook]  

### Additional context
There should be a general conecpt about all expanding or not expanding lists like this.

Because of #2479 no lists should be displayed to the public at all. Though, the single user should see (only) whome he is following.

### See additional informations in the dialog below

**Comment by mattwr18** [comment]
We still very much want this feature, maybe there are duplicate issues though?

**Comment by Tirokk** [comment]
There is a duplicate and already closed issue #2336 .

Text there … (updated)

Several users demanded:
Enlarge the ‚following' and 'followed by‘ lists on user profile on click.

![Bildschirmfoto 2019-11-24 um 10 31 08](https://user-images.githubusercontent.com/25344101/69493098-b8731380-0eaa-11ea-8d09-d9651427a366.png)

### User Problem


I and other users like to see all who I do follow and all who do follow me.

### Implementation, Design & Layout


- Making the information text under the lists clickable and then show the whole list.
- Have a ’show less’ clickable text under the full list to make it short again. Like on the comments of posts.

### Additional context


Need:

- The user themselves (like myself and others I know) like to see whom they follow and who they are followed by. Otherwise I can not manage it.

Privacy issues:

- There should be a privacy setting to show or hide these informations to others (no one, just friends or public as examples).

**Comment by alina-beck** [comment]
Update from today's dev meeting:
- add a `ghost` button to the top of the list (see `comments` for design inspiration)
- the button should say `show all`, then switch to `show less` when clicked
- `on click` request a list of all followers from the backend and display them as a long list

**Comment by alina-beck** [comment]
@DennisHack just added that the second list should disappear entirely. Other users should only see who one is following, not who one is followed by.

**Comment by rbeer** [comment]
How about an overflow container with filter capability for the users with lots of connections?
![follower-list](https://user-images.githubusercontent.com/3411649/76587376-f17bd600-64e3-11ea-89ee-0337ec1d3f9d.gif)

>Other users should only see who one is following, not who one is followed by.

I guess that only goes for public profiles, right? Users will still be able to see both sides?
I'd make it a reusable component then.
