### ISSUE TITLE
🐛 [Bug] extend Title to 100 characters

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#1812]
## :bug: Bugreport
The Title for new posts is too small.
![title64](https://user-images.githubusercontent.com/13457963/66187056-2c9bf280-e684-11e9-91ad-a2205c4847fd.png)
![titleshort](https://user-images.githubusercontent.com/13457963/66187062-2f96e300-e684-11e9-9666-ab5794d0877e.png)

### Expected behavior
It should be possible to at least fill in a title from Youtube with 100 characters in length

### Version & Environment
 Type: [Desktop]      
 - OS: [Linux]      
 - Browser: [Firefox] 
 - Version [69]  
 - Device: [Notebook]  

### Additional context
This is the result of a talk with Dennis. Also a couple of community members told about that.

**Comment by SherSpock** [comment]
Seems like the code below might be the problem, assuming `menuModalsData` is being used to populate the `PostCard` component. 

`        this.post ? this.$filters.truncate(this.post.title, 30) : '',`

This is from my *very* fallible brand-new-to-the-project eyeballing of it. But it's not the `Post` model that's doing the truncating.

Why isn't it called `PostCard.Vue` btw?

If nobody's taken a crack at this by tomorrow (and if you want to feel free) I will likely take a run at writing a failing unit test on the 9DaysOfVue screencast. If I can get the failing test going I'll try to make it pass, if I make it pass I'll PR it.

**Comment by mattwr18** [comment]
I am a bit confused by this issue, to be honest, but I wanted to reply since you were looking at maybe having a look @SherSpock 
I think that the `menuModalsData` is used to pass down data to the `ContentMenu.vue` so that when a user clicks on `Report Post` the title of the `Post` is shown to ensure they really want to report the post with the title
![Screenshot from 2019-10-06 02-47-06](https://user-images.githubusercontent.com/26943915/66262585-b4e4d980-e7e3-11e9-9a0e-b6e71d99f655.png)
![Screenshot from 2019-10-06 02-47-17](https://user-images.githubusercontent.com/26943915/66262586-b7dfca00-e7e3-11e9-8f67-0f4bc82519fa.png)

I'm not sure exactly what is meant by the issue since the title in the screen shots is not being truncated at all, it is taking up multiple lines because there are 3 columns of `Post`s, but the title is complete.

We named the component `/PostCard/index.vue` and then later agreed it should be `PostCard.vue` and have not updated it, but certainly could.

@datenbrei could you please clarify this issue?

**Comment by SherSpock** [comment]
Thanks for the promptness and clarity of your response Matt. Helps a lot!

I think I'll leave this until we hear back from product

**Comment by datenbrei** [comment]
The 64 characters was just an arbitrary decision. So changing to 100 char may be a one-line-change?

well, @mattwr18 told me, that there is also an issue with character counting when having HTML in. So some kind of cleaning would be good.

**Comment by ogerly** [comment]
@SherSpock  Sorry I skipped you. I didn't read everything and just did it fast because I used to work on it and knew where it was. 
the next time I pay attention. It's good if you can get assignees for one issues

**Comment by SherSpock** [comment]
It's no problem at all 🙂
