### ISSUE TITLE
🐛 [Bug] Post with just a video can't be saved

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#1876]
## :bug: Bugreport
Post with just a video can't be saved.
![embed no](https://user-images.githubusercontent.com/13457963/66646191-c257f480-ec25-11e9-9bc4-0250dfe33bb3.png)

### Steps to reproduce the behavior
1. Write a news article
2. add a title and a video
3. You can't send it.

### Expected behavior
It should be possible

### Additional context
If this needs another decision, just get in discussion with me.

**Comment by ogerly** [comment]
and only on the url? they're also displayed that way. 
i don't think it's a good idea

**Comment by ogerly** [comment]
the sense goes absolutely past the thought of HC if we allow that only a video can be posted. 
i would have set the limit for text at minimum 120 characters. 
people should be made to write some meaningful text. otherwise a part only posts a link or an embed. 
i don't think that's good. 
it is not a bug!
i would like to close the issuse.

**Comment by alina-beck** [comment]
In yesterday's meeting we agreed that users should not be able to add a post with just a video but that we need better form validation – here is an issue for that: #2119
