### ISSUE TITLE
🚀 [Feature] Notifications page with all notifications

### ISSUE THREAD

**Issue by mattwr18** [Human-Connection/Human-Connection#1974]
## :rocket: Feature

```
As a user
I'd like to have a page listing all my notifications
So that I can find old notifications and the posts related to them
```

**Comment by Tirokk** [comment]
That is a fitting description, because the report notifications are not in the code now. @mattwr18 
May you could add a steady link to this list in the notifications menu underneath the notifications.

I have the impression the notifications menu should open always in this case to get quick to this link, even when there are no notifications?

**Comment by mattwr18** [comment]
Yes, I have added a link there as well, now I just need to figure out how to make it visible if there are so many notifications that a user needs to scroll down the list. Cause it's not good user experience to make them scroll all the way down to click on the link. 
What about the page itself? Would you expect it to look similar to the `Reports` page for moderation?
I have this so far, but I guess it each notification is too big for the page
![Screenshot from 2019-10-21 19-47-16](https://user-images.githubusercontent.com/26943915/67270235-8b50d100-f4b8-11e9-949f-03d5770ab09f.png)
