### ISSUE TITLE
💬 [Question] Stick to Vue or switch to React?

### ISSUE THREAD

**Issue by alina-beck** [Human-Connection/Human-Connection#2044]
## :speech_balloon: Question
We need to decide which frontend framework we want to use going forward.

### Background
Much of our frontend code is in need of refactoring. We should aim for:
- smaller components
- semantic HTML
- less nesting
- styling with CSS instead of HTML elements

The planned migration of the styleguide involves:
1. rebuilding most of the components from the [current styleguide](https://github.com/Human-Connection/Nitro-Styleguide) directly in our main codebase, following the above guidelines
2. replacing some of the old components (e.g `ds-flex` which is a styling component) with CSS rules
3. splitting up many of our large components into smaller, reusable parts

Doing this means we will touch – and improve! 😎 – most if not all our existing components. This process will take time and run alongside our regular development. We still want to develop features! With this in mind...

## Reasons for switching to React
- We have frontenders with a lot of React (and little Vue) experience on the team (speaking for myself + @Kachulio1), so rebuilding/developing new components would be faster with React
- React is the wider used framework, with more maintainers, a bigger ecosystem, more third-party solutions to choose from (Vue is basically maintained by [one guy](https://github.com/vuejs/vue/graphs/contributors) – not a very high [bus factor](https://en.wikipedia.org/wiki/Bus_factor))
- There are more React developers out there, so finding new contributors might be easier

## Reasons for sticking with Vue
- Most of the team is used to working with Vue
- We already have working solutions for complex features (like the `Editor`) in Vue
- Vue positions itself as a framework _'from the community for the community'_ which sounds like a better philosophical fit than _'facebook's baby'_ React
- @roschaefer is currently teaching his students how to use Vue and it would be _awesome_ if they could contribute
- migrating to React would mean having to support two frameworks at the same time over the course of several months which can be confusing for new and old contributors alike

**Comment by MarcoBomfim** [comment]
Couple of points from me (even though my opinion might be biased, since I'm also more experienced with React): 
- React will soon deprecate Class-based components (or so they say), in favor of the hooks like [useEffect Hook](https://reactjs.org/docs/hooks-effect.html). Personally, I think this clears the code a lot, making it a lot more readable, and inviting for new collaborators, as well as more maintainable.
- They just recently announced [Concurrent Mode](https://reactjs.org/docs/concurrent-mode-intro.html), which may provide a much nicer feel for users, and the UX folks in general. Again, due to my low XP with Vue, I'm not sure if it provides such feature. 
-  Just recently, on the last company I've worked on we had to migrate a React app to a mobile application. React Native made it feel extremely easy, even though the deployment is a little fuzzy. And migrating components were just a matter of performing some minor refactor to the code logic/structure.

I'll research a little more to try contributing further regarding this topic, and will edit this comment if something else shows up.

**Comment by alina-beck** [comment]
In our core team meeting today we decided to stick with Vue because at this point the cost of migrating to React seems to outweigh the benefits.

**Comment by mattwr18** [comment]
here is a link to our latest conversation
https://github.com/Human-Connection/Human-Connection/wiki/2019-10-28-Developers-meeting

**Comment by Kachulio1** [comment]
Noooooo!

**Comment by Kachulio1** [comment]
@MarcoBomfim where did they say that coz I don't think they'll deprecate classes.
they wouldn't do the same thing that made Angular lose its popularity. see here [breaking-changes](https://reactjs.org/docs/hooks-intro.html#no-breaking-changes)

**Comment by Kachulio1** [comment]
@roschaefer it would be nice if you didn't have to teach your student's "alone". don't you think?

**Comment by Kachulio1** [comment]
just commenting out on Reasons for sticking with Vue 👆

**Comment by MarcoBomfim** [comment]
> @MarcoBomfim where did they say that coz I don't think they'll deprecate classes.

My bad, I've misread their comment on https://reactjs.org/docs/hooks-intro.html. They actually meant that there is **no** intention of deprecating classes. But there is a [gradual adoption strategy](https://reactjs.org/docs/hooks-intro.html#gradual-adoption-strategy) to use hooks instead.

**Comment by Kachulio1** [comment]
> here is a link to our latest conversation
> https://github.com/Human-Connection/Human-Connection/wiki/2019-10-28-Developers-meeting



> In our core team meeting today we decided to stick with Vue because at this point the cost of migrating to React seems to outweigh the benefits.

![Alt Text](https://thumbs.gfycat.com/UnpleasantDapperGreatargus-small.gif)

**Comment by mattwr18** [comment]
hahaha, not a fan of the decision, I suppose @Kachulio1 ??
Did you read the reasons behind the decision? Although, not complete they do help to give the thinking behind it.

**Comment by alina-beck** [comment]
@Kachulio1 let's learn some Vue together, shall we? :grin:

**Comment by Kachulio1** [comment]
![Alt Text](http://24.media.tumblr.com/tumblr_lspv1jjXi31qii6tmo1_400.gif)
