### ISSUE TITLE
Pro-Contra

### ISSUE THREAD

**Issue by Mastercuber** [Human-Connection/Human-Connection#21]

**Comment by appinteractive** [comment]
We will start creating projects for the features.

**Comment by realB12** [comment]
I do not understand this issue: could somebody explain?

**Comment by appinteractive** [comment]
Visit http://human-Connection.org and see the features discribed there. 

We will move the process for features into GitHub projects and create separate tasks. That’s just a placeholder/reminder. The same for the other related feature issues.

**Comment by realB12** [comment]
Is there something like an overall requirements list where we can see priorities and schedules for the features to come. So far I have just checked the issues and honestly I do not find a pattern in it. Is it that everybody just works on the things he want's to work? Is there an authority who decides where the money shall go? 
For instance, I have seen lenghty discussions about "distributes file system" but I cannot see why THIS is so important now, whether we have a budget for this and what depends on this, etc. 
Although we have now a single point of entry into project documentation I am not sure whether it is just incomplete or whether we just do not have all the stuff you need to coordinate things and/or put activities into an overall context and meaning.

**Comment by Lulalaby** [comment]
"budget" ^^ which budget, every member here does it for free, as far as i know.
Is it important? Yes, because it is already anounced in the alpha, and the users are waiting for it.

**Comment by realB12** [comment]
@mimicc83 Your quote: "common in decentral dev teams"
Yes, there are such teams. But they are not sponsored by public, tax-free money which is different for HC. 
I think, that the EVE£RYBODY should have a saying on priorities, or at least priorities should be up to discussions. It is still NOT TRANSPARENT who the "WE" is, How have given the "WE", when and which competencies. And when the WE finally starts to bully people, deleting comments and kicking out other commenters, this project goes away from the HCs own principles and even from OS best practice.

**Comment by Lulalaby** [comment]
Can you actually do anything other than complain?

If you can't behave and provoke other people, then don't wonder about this.

**Comment by mimicc83** [comment]
Everybody has a say as long as it is:

a) valuable input
b) technically possible
c) helps the platform grow
d) for the greater good

there will be no further discussion on this. You can join the discussion and have YOUR say on discord or here, given the points above match.

**Comment by realB12** [comment]
Don't blame others,  when you are not able to run a discussion board or issues. 
Have a look to successful projects and try to come somehow close to them. 
Blaming contributors for doing the wrong things,  because YOU cannot provide structure nor guidance is selfish, introvert,  bad style and wrong.
Further: GitHub for most successful projects has turned out to be ok running the project. I do not see why you are running against OS/GitHub best practice for running your small-team discussions on a private, non-secure game-channel for Kids.

**Comment by realB12** [comment]
Don't blame others, when you are not able to run a discussion board or issues.
Have a look to successful projects and try to come somehow close to them.
Blaming contributors for doing the wrong things, because YOU cannot provide structure nor guidance is selfish, introvert, bad style and wrong.
Further: GitHub for most successful projects has turned out to be ok running the project. I do not see why you are running against OS/GitHub best practice for running your small-team discussions on a private, non-secure game-channel for Kids.

**Comment by christianeiselt** [comment]
Is this thought to be like https://www.kialo.com? I'd say this would be a good one to get inspired of...

**Comment by mimicc83** [comment]
@christianeiselt exactly! Good find, thanks! :)

**Comment by ulfgebhardt** [comment]
closed in favor of https://github.com/Human-Connection/Human-Connection/issues/430
