### ISSUE TITLE
🚀 [Feature] Refactor deprecated slot syntax

### ISSUE THREAD

**Issue by mattwr18** [Human-Connection/Human-Connection#2117]
## :zap: Refactor

Following https://vuejs.org/v2/guide/components-slots.html#Named-Slots

We are using deprecated syntax in various places in our code base

In short, `<template slot="index" slot-scope="scope">` can be refactored to `<template #index="scope">`

Motivation for this change, and more examples can be found here https://github.com/vuejs/rfcs/blob/master/active-rfcs/0001-new-slot-syntax.md

**Comment by mattwr18** [comment]
Let' make this into a bounty issue @Human-Connection/hc-dev-team ??

**Comment by alina-beck** [comment]
Hah, yes! I just had the same idea and started adding an issue for it... Here are some more hints:

Summary of the [official Vue docs](https://vuejs.org/v2/guide/components-slots.html) and [our own guidelines](https://github.com/Human-Connection/Human-Connection/blob/bbd678caa6215865df78aff90de4a518d5d39136/webapp/vue.md#we-use-shorthands):
- define default slots as `<slot />` and named slots as `<slot name='slotName' />`
- use the shorthand `#default` or `#slotName` instead of `slot='slotName'`
- make sure the `#someSlot` attribute is only set on `<template>` elements

**Comment by rbeer** [comment]
done in #3258
