### ISSUE TITLE
🚀 [Feature] Create Post – consistent form input validation

### ISSUE THREAD

**Issue by alina-beck** [Human-Connection/Human-Connection#2119]
## :rocket: Feature
Validate all fields of the `create post` form in a consistent way. (Ideally, the same system can then be applied to all forms on the network.)

<img width="463" alt="Screenshot 2019-11-05 at 10 44 14" src="https://user-images.githubusercontent.com/11694483/68188570-80b73100-ffba-11e9-873d-2688164ddeec.png">

### User Problem
It is unclear which parts of the `create post` form are required and what kind of input is valid. Many users don't know that they have to select `categories` or that a video by itself is not enough content (see #1876).

### Implementation
I would like it if the `title` field and the main `content` editor could be validated with visible feedback _after_ the user entered their input and left the field (i.e. onBlur). Validating input too early (when the user just started typing) or too late (when the user tried to save the post) can lead to frustration.

Open questions / challenges:
- Since images are optional they probably don't need validation?
- It is unclear if the third-party editor allows for the behavior proposed above
- We need a clear message to explain to users that the length of the URL of an embed link does not count toward the minimum content length
- We need to come up with a solution for `categories`
- Is the `language` required? Should it be pre-filled?
- In addition to the validation (after user input) we could also mark required fields (before user input) – but how?

### Design & Layout
The visual feedback for `title` and `content` could look like this:
<img width="825" alt="Screenshot 2019-11-05 at 10 52 39" src="https://user-images.githubusercontent.com/11694483/68189108-bdcff300-ffbb-11e9-8101-e3a6cde4329b.png">

Question: Do we also want to give feedback for valid content (e.g. a green border and a checkmark)?

### Validation (How can we make sure that this feature solves the above problem?)
- no more bug reports about videos as posts not being accepted
- we could measure if users are faster when creating posts (are any analytics tools set up?)
- developers can see if new contributors are less confused when creating a post in a pairing session

**Comment by datenbrei** [comment]
My answers to that:

- Images can't be validated. it needs just to be in a supported image data format.
- 3rd-party editor: possibbly the data can be validated at submit time?
- Why not just allow empty content? If a content is three characters in my point of view it is not better than an empty one. In trying to enforce a good user behaviour we introduce problems we would not have otherwise? We also should think about, why just a video would be (is it) a bad thing.
- For categories I just see the way that we have a message popping up or so at submit time.
- Language is required. We later will have a filter for it.
- Since I know just about normal HTML I can't say much about the components used here at us....

**Comment by alina-beck** [comment]
> 3rd-party editor: possibly the data can be validated at submit time?
the idea is to have _consistent_ validation – I think it just adds to the confusion when we check some fields right away, others `onSubmit` and others not at all :confused:

I think we will need to do some research and try out if we can achieve this with the editor. I'm not saying it's not possible! I just don't know if it is.

> Why not just allow empty content? If a content is three characters in my point of view it is not better than an empty one. In trying to enforce a good user behaviour we introduce problems we would not have otherwise? We also should think about, why just a video would be (is it) a bad thing.
Hehe, great question! I think @ogerly was suggesting to introduce a higher limit (`160` characters?) to ensure we get more meaningful content. But yes, in some cases a video alone _can_ be valuable content. I guess it is just a decision we will have to make. @DennisHack, maybe?

> For categories I just see the way that we have a message popping up or so at submit time.
It's a possibility. But again, I don't think this would be a very consistent or smooth behavior. Maybe we should think about how we can make it clear from the very beginning that this is `required`. Splitting up the post creation into separate steps could be one way... (Not a very easy one, though! :wink:)

> Language is required. We later will have a filter for it.
Ok, good point! 👍

**Comment by sushidave** [comment]
@alina-beck Hello Alina. Those are very helpful features for users, thanks very much for this issue!
> Since images are optional they probably don't need validation?
I would suggest to show supported image formats in the placeholder, see #1949 .

**Comment by datenbrei** [comment]
I asked @DennisHack for how he would like this to behave.

**Comment by alina-beck** [comment]
@datenbrei have you seen the PR @ogerly has put in? :point_up: He proposed a design that I like a lot and think has great usability! It might need some fine-tuning but the idea is really good. :grin:

**Comment by datenbrei** [comment]
@alina-beck I've seen this, but I saw: Robert's work is better. ?!?!?  

Anyways, I talked to @DennisHack . We agreed, that, sinece a post with three characters is as nonsense as an empty one we should allow empty posts for now, so that people just posting an URL do not run on errors and can post their videos.

**Comment by HelixX23** [comment]
Hi, does the input validation at the server side validate the same rules like the client side?
(Just to make sure there is a protection for unexpected browser behavior)

for image input validation it would be nice to transform the input image at the server side to scale it to a maximum size. The image maybe should be transformed and rewritten/recalculated anyway because of the direct browser presentation of this input to the user side. This should remove also eventually hidden content in images...
(hidden image content example: https://www.mobilefish.com/services/steganography/steganography.php)
