### ISSUE TITLE
🚀 [Feature] Search by hashtags

### ISSUE THREAD

**Issue by alina-beck** [Human-Connection/Human-Connection#2143]
## :rocket: Feature
Users should be able to search by hashtags by entering a keyword in the search field.

### User Problem
At the moment users can only find posts by hashtag by navigating to a post and clicking the hashtag in its content. This takes a long time and can be very frustrating, especially since they first need to _find_ a post that contains the hashtag they are interested in.

### Implementation
The list of search results should include a section with `hashtags` where the relevant hashtags are listed. Selecting a hashtag initiates the hashtag search the way it is working now (i.e. displaying the hashtag on top of a page with posts containing that hashtag).

### Design & Layout
The hashtag results should look similar to the post and user results in this example:
![Screenshot 2019-10-29 at 17.14.14.png](https://images.zenhubusercontent.com/5d1ef2c6fa967b04b3b34866/5818038e-92f1-4457-a9b1-44bc258e4e56)

### Additional context
This is **Step 3** in our search implementation – see #2146.
**Step 1** is adding users to the list of search results: #1463.
**Step 2** is limiting the number of search results to 15: #2142.

related to #1068

**Comment by hermann-san** [comment]
in regards to hashtags.  Is it the expected behaviour that hashtags are case sensitive? 
The problem I  see is that there are many duplicated hashtags that are not really needed.
e.g.  #cando  #CanDo #Cando   . 3 hashtags for the same thing.  
Or   #Frieden #frieden  #Berlin #berlin
Wouldn't it be better if hashtags were not case sensitive?
In some cases if gives a little more flexibility, but in most cases I see it as redundant.

**Comment by DennisHack** [comment]
Please make it non-case sensitive, for example, if I look for JulianAssange, I want all of it at one time and not searching different possibilities.

**Comment by mattwr18** [comment]
I don't think that is the question @DennisHack ... I believe the question is whether we should be creating separate `nodes` for hashtags that have different casing.
We talked about this in our standup today, and we agreed that we would create separate nodes because we want to display the hashtag with the casing the user prefers, but that we would collate the query to include all hashtags that only differ in casing.

**Comment by hermann-san** [comment]
This is probably a different feature, but it would be nice if it would be possible to connect hashtags
i.e.   #Assange and  #JulianAssange  belong together and it would be nice to link them . For example when I search for #Assange, then I also get results for #JulianAssange 
However , this is something that humans needs to decide which hashtags belong to each other and it should be done only if it is very clear that the hashtags really belong to each other  in order to avoid false linking.

**Comment by Mogge** [comment]
@hermann-san This is a great idea. May be create a Feature report for it? Something like a page to manage hashtags? But we will not be able to do this in the nearest future.
