### ISSUE TITLE
🐛 [Bug] Remove potentially sensitive information from JWT encoded token

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#2202]
## :bug: Bugreport
While I'm writing [the slides for my lecture](https://docs.google.com/presentation/d/1UiBKO0v0dUlCIH1bb6O6UbbH30IURjqi0D30OBieS5I/edit?usp=sharing) I see that JWT documentation warns about putting sensitive data into the token. We put the `email` of our user there. We never use the `email` when we decode the token. Let's get rid of it.

### Steps to reproduce the behavior
1. Get a Json Web Token: http://localhost:4000/
```graphql
mutation {
  login(email: "user@example.org", password: "1234")
}
```
2.  Copy+paste the token here https://jwt.io/
3. See the email in the base64 decoded payload

### Expected behavior
E-Mail shouldn't be there.

### Additional context
Here is where we decode the token: https://github.com/Human-Connection/Human-Connection/blob/master/backend/src/jwt/decode.js

Here is the JWT documentation: https://jwt.io/introduction/

> You also should not store sensitive session data in browser storage due to lack of security.

**Comment by roschaefer** [comment]
@steffi201028 I think it is enough to remove the `.email` from this line here: https://github.com/Human-Connection/Human-Connection/blob/master/backend/src/jwt/decode.js#L18

If you push a feature branch and create a PR from there, we can see if removing the `.email` breaks anything - I believe it's completely not required and can be removed. But we will see.

**Comment by steffi201028** [comment]
@roschaefer Turns out removing the .email from https://github.com/Human-Connection/Human-Connection/blob/master/backend/src/jwt/decode.js#L18 does not have the desired effect.
I found that using an explicit delete statement here

https://github.com/Human-Connection/Human-Connection/blob/master/backend/src/jwt/encode.js

does the trick. Not sure if this is correct, locally at least it does not break anything.
