### ISSUE TITLE
🐛 [Bug] Scrolling fails after a while

### ISSUE THREAD

**Issue by DennisHack** [Human-Connection/Human-Connection#2253]
I know that on Windows AND Ubuntu with CHROMNE Browser, the problem appears.
I recorded it, so you can have a own look:
https://www.youtube.com/watch?v=zopX8OyzaIA&feature=youtu.be

Screenshot:
<img width="732" alt="scroll-bug" src="https://user-images.githubusercontent.com/13457963/69944850-897f2200-14e8-11ea-88ae-4520186b1946.png">

I have 64GB RAM, 32GB Graphics Card NVIDIA Quadro 4000

As the problem lasts for many weeks, it is not related to a special version of chrome I think, as I have installed Chrome (newest version) not long ago.

**Comment by mattwr18** [comment]
I think this could maybe be due to the images being loaded slower than a user is scrolling, and the layout getting messed up somehow. The layout is recalculated based on the height of the image.

For now, try scrolling slower :stuck_out_tongue_closed_eyes: ... Just kidding.

I would try to have a look at this, https://github.com/Human-Connection/Human-Connection/issues/2254, which is an issue @Tirokk created... maybe if we can add a property to the `Post` like `imageHeight` and use that to add a placeholder that then gets replaced by the image when it comes through... 

Would need to see if we even know the height of the images, or if we can add it for future images added...

**Comment by roschaefer** [comment]
![2019-12-02-182534_1920x1080_scrot](https://user-images.githubusercontent.com/2110676/69981141-02569c00-1532-11ea-947d-bdea059277b3.png)


I'm afraid we have to test this in production to see if the error is fixed.

**Comment by datenbrei** [comment]
I reopened this one, because @DennisHack reported, that his issue ist still not yet solved.

**Comment by mattwr18** [comment]
@Tirokk could you please update this issue with the info you said you found out about it, please!

**Comment by Tirokk** [comment]
Yeah.
May you can have a look in this and give your opinion? @mattwr18 @alina-beck 

I have find this:
https://github.com/rachelandrew/gridbugs/issues/28

**Comment by alina-beck** [comment]
Wow, good find @Tirokk! That's... _very_ bad news. And it looks like this won't change anytime soon: https://bugs.chromium.org/p/chromium/issues/detail?id=688640

So, what now? Rewrite the `MasonryGrid` without using `CSS grid` – i.e. without achieving the same effect (see comments on https://github.com/Human-Connection/Human-Connection/issues/378)? Redesign the whole `index` page? 🤷‍♀

**Comment by datenbrei** [comment]
I would not recommend to work around browser bugs - at least not, if the problem arises after 1000 posts. Using a grid is a modern way for structuring this kind of data. That's the right way.

**Comment by alina-beck** [comment]
It is! And the Chrome developers admit it's a problem – but one that's not easy to fix and has therefore been lying around unsolved for years... So I don't think waiting for a browser-side solution is an option.

The only other "workaround" I could think of is explicitly recommending to use `Firefox` on our part – i.e. adding a note on the login/signup page saying something like `Human Connection runs best on Firefox`. I also think it's a nice ideological fit, so that's a bonus. :wink:

**Comment by datenbrei** [comment]
As a solution: We will recommend Firefox for HC
