### ISSUE TITLE
🚀 [Feature] animate the CREATE BUTTON or the SHOUT BUTTON

### ISSUE THREAD

**Issue by DennisHack** [Human-Connection/Human-Connection#2376]
## :rocket: Feature
Wouldn't it be nice to have an elegenat animated CREATE and SHOUT Button? 
https://youtu.be/rSnwD2tn-sA

### User Problem
Can't see the important buttons from rightaway

### Implementation
Change design to animated
### Design & Layout
be creative!

### Validation
We will see more feedback like more shouts in generall

### Additional context
"Push the button!"

**Comment by erhardtstiefel** [comment]
Although I'm not a fan of animated action buttons and feel very comfortable with the quiet user interface of HC, a discreetly animated suggestion to become active to make a contribution is certainly appropriate. Animated in the rhythm of the heartbeat, with easy to understand symbols (heart & mind?) and in warm shades.

**Comment by alina-beck** [comment]
Animated buttons scream for attention – which is great on a landing page (for example), when you want to push your users towards exactly _one action_.

On our platform there are many different actions we want our users to complete and already many things competing for our users' attention – the `create post` button, the `notifications menu`, the `posts` in the feed, especially the `pinned post`... When I just want to see what's new a pulsing button can be very distracting.

But there are other ways to direct our users' attention! We want them to write more posts?
- How about offering them the possibility to write a new post from _every_ page on the network, not just the `index` page?
- Or replacing the floating action button in the bottom right corner with a more prominent button on top of the page? (Or why not both?)
- We could also try to pin fewer posts (I don't think I've ever seen the network without a pinned post since we introduced the feature...)
- Or remove the very prominent `notifications button` from the header and instead place new notifications on a `user dashboard` and add the counter to the `avatar` instead.

And the `shouts`?
- How about making the button round and green? I admit, it is quite subtle at the moment.
- Or make it a floating action button, as proposed in this issue: #2289?

I think we should first decide what we want to achieve and where the focus of our users should be and then think about how to get there. 🙂

**Comment by DennisHack** [comment]
More on top, I would recommend this type: 
![image](https://user-images.githubusercontent.com/24620721/70386621-2a635680-199b-11ea-954e-dd60e791988c.png)

Please contact me/appointment and let's talk about it to go through the options. THANKS!

**Comment by DennisHack** [comment]
https://preview.uxpin.com/24a2ab8adcd84f9a763d87ed27251351225e0ecd#/pages/99768901/simulate/no-panels?mode=i

**Comment by erhardtstiefel** [comment]
Guten Morgen Dennis,
ich kam gerade aus dem Bad und wollte kurz nachsehen, ob meine ersten fünf
Pull Requests durchgegangen sind.
Dann sah ich deine mail und als ich auf den Preview Link unten klickte, war
ich sehr überrascht.
Soll unsere Seite einmal so aussehen? 
Die würde mir natürlich auch viel besser gefallen, als es der jetzige Stand
ist.
Aber das ist sicher noch ein weiter Weg ...
Ich mach es heute kurz, denn heute ist ja der "Tag des Herrn" und da sollen
wir ja die Arbeit ruhen lassen.

Weil ich derzeit wegen eines Muskelfaserrisses nicht schmerzfrei laufen kann
 gehen wir heute nicht zur Kirche.
Dafür sehe ich mir nachher den Gottesdienst vom ERF um 11.30 Uhr auf Bibel
TV an.
https://www.erf.de/erf-mediathek/sendungen-a-z/erf-gottesdienst/4929?reset=1

Ich wünsche dir und deiner Familie einen gesegneten 2.Advent!
Liebe Grüße,
Erhardt
 
-------Originalmeldung-------
 
Von: DennisHack
Datum: 08.12.2019 09:24:15
An: Human-Connection/Human-Connection
Cc: Erhardt Stiefel;  Manual
Betreff: Re: [Human-Connection/Human-Connection] 🚀 [Feature] animate the
CREATE BUTTON or the SHOUT BUTTON (#2376)
 
https://preview.uxpin
com/24a2ab8adcd84f9a763d87ed27251351225e0ecd#/pages/99768901/simulate/no-pane
s?mode=i

**Comment by alina-beck** [comment]
replaced by #2783
