### ISSUE TITLE
Stop users from interaction with my data

### ISSUE THREAD

**Issue by Nick-HC** [Human-Connection/Human-Connection#287]
**Is your feature request related to a problem? Please describe.**
From my experience, people comment in my posts who draw attention from the topic to themselves. This is annoying and distracts from my post.

**Describe the solution you'd like**
A personal list, in my profile settings, that allows me to determine who can not interact with my posts.

**Describe alternatives you've considered**
Restrict visibility for my own content: An unwanted user would not see my contributions in his or her news feed. That way an disliked user would not notice my posts and probably don't write comments. However this would not stop him from writings comments, e.g. if he/she follows a deep link.

**Additional context**
![unbenannt](https://user-images.githubusercontent.com/47418179/52411779-2e092100-2add-11e9-9a81-dc0e2fce55a3.jpg)

**Comment by mattwr18** [comment]
I would like to close this @datenbrei @Tirokk @alina-beck @roschaefer @ogerly as the problem the user brought up, and it's possible solution have been implemented with `Block User 1.0(?)`...
We've since "decided" to revisit the solution, and have ` Blacklist` for content, and `Block` for users... see https://github.com/Human-Connection/Human-Connection/issues/1724 for a continuation of the up-to-date conversation.
@Nick-HC brings up another idea that has been made into an issue here https://github.com/Human-Connection/Human-Connection/issues/1264, with an implementation idea.
Can we close this? or do others think it should be kept open?

**Comment by Tirokk** [comment]
So then I decide to close it now!
