### ISSUE TITLE
[Feature] Authentication

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#298]
```gherkin
Feature: Authentication
  As a database administrator
  I want users to authenticate
  In order to attribute posts and comments to their authors
```

**Comment by datenbrei** [comment]
@roschaefer Who should that be, a database admin? My idea was to stay on a high level and attach more detailed tasks under beneath, like frontend/backend tasks or authentication, which is just one feature which is account related. The account later may get more data, like "verified person" or such, which may not automatically have to do with authentication. What do you think?

**Comment by roschaefer** [comment]
@datenbrei a database administrator is the maintainer, in our case the Human Connection gGmbh. The reason for changing the description is that I think it's not the author who wants to authenticate. It's the other users and the maintainer of the database who want authors to authenticate. Otherwise it would simply not be possible to attribute user content to their authors.

Regarding nesting: I would keep things stupid. This user-story has now one purpose and that is to connect users to their data and their posts. At the moment this would be already implemented. A feature like "verified person" probably has a different purpose, hence a different user-story. I would not inter-connect issues if this does not serve a purpose (.ie having a check list or a release).

**Comment by ulfgebhardt** [comment]
Related https://github.com/Human-Connection/Human-Connection/issues/343
