### ISSUE TITLE
🐛 [Bug] Post page crashes when post author is null

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#2985]
## :bug: Bugreport
We're trying to show or not show the comment form depending on `post.author.blocked`. Unfortunately this will produce an error if the `post.author` is null (anonymous user, deleted user)

### Steps to reproduce the behavior
1. Seed your database and then remove the author from the post manually
2. Visit the post page of this post in your browser
3. App crashes while trying to render the template

### Expected behavior
Comment form should be visible.

**Comment by mattwr18** [comment]
I will challenge this slightly, only in the sense that I don't think it is so reproducible.
What I did...
1) I blocked `louie@example.org`
2) logged in as Louie, and deleted my account, but left my Posts and Comments for the community
3) visited the post page of the now deleted user, and there in no `null` pointer error because we don't delete the entire node, when someone asks for their account to be deleted.
![Screenshot from 2020-02-04 15-30-04](https://user-images.githubusercontent.com/26943915/73753575-3b460380-4763-11ea-9f0f-166d239a7eb9.png)

To your first assertion that the author is `Anonymous`, we apparently define this like so in our app,
```
isAnonymous() {
  return !this.user || !this.user.name || this.user.name.toLowerCase() === 'anonymous'
},
```

Of these, the only one that could possibly throw a null pointer error is `!this.user`, but under what circumstances would this occur? If they were manually deleted from the database as you suggest in your steps to reproduce. I don't see why we would want to do this, but if there were a reason, we would have an issue with many null pointer errors, no?

I'm not saying that we might not want to merge your `PR`, just would like some more clarification, please

**Comment by roschaefer** [comment]
@mattwr18 you have a really good point. i'm making the app robust against scenarios that cannot happen apparently. In general I'm against adding these checks. I call this "Angst code" (fearful coding).

However, the least thing we should do is to put an exclamation mark [here](https://github.com/Human-Connection/Human-Connection/blob/master/backend/src/schema/types/type/Post.gql#L116).

Why do we have the hard-coded check for ` this.user.name.toLowerCase() === 'anonymous'` in our code base?

**Comment by mattwr18** [comment]
it was copied and :spaghetti: from the styleguide... you know better than I do how this worked in the old alpha, and whether or not we should keep it, but I guess if a user chose the name `Anonymous`, then it would also display the `eye-slash` for their avatar image.

To make it non-nullable?

**Comment by mattwr18** [comment]
@roschaefer any update on this?
