### ISSUE TITLE
[Epic] Federation

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#327]
```gherkin
Feature: Federation
  As a user of the network 
  I want to be able to decide to let other people outside of the network itself follow me or not and also to be able to follow people from other networks
  In order to make my own public content available to the world outside of the network itself and keep informed about new contributions of others.
```

**Comment by roschaefer** [comment]
@datenbrei I drop this epic in favour of a dedicated release: https://app.zenhub.com/workspaces/nitro-5c0154ecc699f60fc92cf11f/reports/release?release=5ca29c0356c0222e8cdb6e47

**Comment by ulfgebhardt** [comment]
Why was this closed? @roschaefer

**Comment by roschaefer** [comment]
In my [comment](https://github.com/Human-Connection/Human-Connection/issues/327#issuecomment-478797573) I explained that I drop this epic because it is a "grouping" issue, not a single-purpose user-story.

"Federation" is a really large set of many user stories and it will be implemented once the entire ActivityPub specification is implemented.
