### ISSUE TITLE
Send out notifications on CreateComment via ActivityPub

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#351]
Similar to #349 we need to send out notifications. The only difference is the `replyTo` attribute which points to the commented post.

**Comment by roschaefer** [comment]
@Mastercuber correct?

**Comment by Mastercuber** [comment]
I can't remember another needed change.

**Comment by Mastercuber** [comment]
@roschaefer Comment in #349 should clarify.

**Comment by Mastercuber** [comment]
@mattwr18 FYI I've tested the mentioning on mastodon. To get a notification not only the addressing to the specific user is needed but also the mention tag.

**Comment by mattwr18** [comment]
great! I will be working on this next!! any chance you'll be free to pair @Mastercuber, I can't remember when you said you'll be back from a little time off after your much deserved break. Congrats! by the way

**Comment by Mastercuber** [comment]
@mattwr18 Thanks! It was harder then I though it will be :grimacing: From Monday on I will stay online in discord, so just send me a message. I will take the time for a pairing. Sorry, that I just told Robert that my plan is to get back to work at 12. of May. Maybe I will delay for a week, because my presentation also delays and another presentation is also pending. But not later than the 20. of May.

**Comment by mattwr18** [comment]
ok, I will go ahead with the implmentation. I think it's important to have time to get your mind off of work now and then, even if I don't do it myself :rofl:
