### ISSUE TITLE
🐛[Bug] All PostCards have the same height - dynamic height required

### ISSUE THREAD

**Issue by ulfgebhardt** [Human-Connection/Human-Connection#378]
### All PostCards have the same height - dynamic height required

max height must be defined

![image](https://user-images.githubusercontent.com/1238238/55478414-fb326380-561b-11e9-9b22-2b1041bb1c95.png)

![image](https://user-images.githubusercontent.com/1238238/58756333-c72dce80-84f6-11e9-86f5-6fec65f2ce43.png)

### Steps to reproduce the behavior
1. Login
2. See Cards
3. All same Height
4. ...
5. Profit

### Expected behavior

![image](https://user-images.githubusercontent.com/1238238/55478455-100ef700-561c-11e9-8e39-919c097a72fd.png)

### Version & Environment
 Type: [Desktop]      
 - OS: [Windows]      
 - Browser: [Chrome Beta] 
 - Version https://github.com/Human-Connection/Human-Connection/commit/e4cfa2403a457032c10b449abeaf3082e1863111  

### Additional Context

Keyword: masonry grid

**Comment by Tirokk** [comment]
Greg told me, on Monday, that he is working on it …

**Comment by ogerly** [comment]
https://github.com/Human-Connection/Human-Connection/issues/961

**Comment by alina-beck** [comment]
As far as I'm aware there are currently three ways of creating masonry layouts – and none of them are ideal:

## CSS column-count
### Pros
- wide support
- works without any JavaScript

### Cons
- only supports top to bottom flow
- probably re-renders and changes the position of posts on _load more_

## CSS flexbox `column`
### Pros
- wide support

### Cons
- requires a fixed height – this will definitely cause issues with the _load more_ functionality
- left to right ordering can only be achieved by setting the position for each post with JavaScript (and is not very reliable)

_Note: Flexbox `row` is not an option because then, per definition, all items in a row have the same height_

## CSS grid
### Pros
- left to right flow is built in
- adding more posts on _load more_ is not an issue

### Cons
- the height of each post has to be calculated based on its content and set in JavaScript
- not supported by IE

There are also some masonry libraries out there – but the ones I know are either heavy-JavaScript or/and CSS grid solutions.

Sooo... Which would you prefer? :blush:

**Comment by appinteractive** [comment]
Hey @alina-beck , I did some research on that topic some while ago (after I build the current Alpha implementation) and was setteling on the CSS Grid option with a bit of JS. There is a nice article on that: https://w3bits.com/css-grid-masonry/
Its only needed for sorting the posts correcly based on height (as you seem to know) :)

1. Its fast (the fastest for us)
2. No one (at least we do not) cares about IE users
3. It does support variable hights

Do you want to implement it? I was looking forward to but Im currently more blocked then I would like to, would be awesome if you take a spin on it.
