### ISSUE TITLE
🌟 [Epic] Future Brainstorming

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#490]
## Issue

Brainstorming a list of ideas for the future …

## Communication

- Implement a good and useful audio and video chat, because we are Human Connection. ( @Tirokk )
  - The services available at the moment have all their problems.
  - May one has to pay a small fee for it …

## Community

- Implement a MeetUp or Event organisation feature. ( @Tirokk )
  - … because we are Human Connection.

## Administration
- Save Users, Post etc. in a folder structure in my profile. ( @Tirokk )
  - To follow should not the only possibility.
  - I like to read things later or like to memories them by themes etc..

## Advanced

- Implement an own kind of WayBackMachine to archive internet content in Germany. ( @Tirokk )
  - Maybe on a different domain or in an even other project.

**Comment by ulfgebhardt** [comment]
@Tirokk can you make a feature request/bugreport for each suggestion? <3

**Comment by Tirokk** [comment]
Yes, I’ll do the next days … @ulfgebhardt

**Comment by mattwr18** [comment]
can we close this @Tirokk ??
I tend to agree with @roschaefer for the most part that it would be nice to have GitHub issues related to 
`FAST`(Frequently discussed, Ambitious, Specific, Transparent) goals https://www.workpath.com/en/magazine/fast-goals-why-fast-is-better-than-smart-for-your-goals/

While I appreciate and like the idea to have a space for brainstorming, it looks like we haven't revisited this since April, and there might be a better forum for us to have regular brainstorming sessions?

**Comment by Tirokk** [comment]
You are right @mattwr18 .
