### ISSUE TITLE
🚀 Add baseURL to cypress configuration

### ISSUE THREAD

**Issue by aonomike** [Human-Connection/Human-Connection#576]
## :rocket: Feature

Add baseURL to cypress config file so that cypress tests are run on a different port than the port that the server runs in.

### Is your feature request related to a problem? Please describe.

When running cypress tests on terminal, I have to switch off anything running my ` localhost:3000` so that the cypress tests can run

### Describe the prefered solution and alternatives you've considered

Add a `cypress.config.json` file with the content `{baseURL: "localhost:3001"}`

### Additional context

Running cypress tests

**Comment by roschaefer** [comment]
Yep, I had the same idea already. I think it's not a totally easy contribution, because you have to re-configure `.travis.yml` for our build server and update the `docker-compose.yml` configurations. But the benefit is obvious: You can run `yarn run dev` in `webapp/` and cypress tests at the same time.

Great issue :+1:
