### ISSUE TITLE
🐛 [Bug] User profile page >> content menu - wrong callback

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#785]
## :bug: Bugreport

Reporting a user now shows a super odd error message.

![bug](https://user-images.githubusercontent.com/2110676/59114541-aa0a5d00-8947-11e9-8bde-6d379a0ff3f8.gif)

This is what I saw in my editor:

![2019-06-07-170946_1920x1080_scrot](https://user-images.githubusercontent.com/2110676/59114583-bc849680-8947-11e9-9596-f3a5861db6f1.png)

You can [find the code here](https://github.com/Human-Connection/Human-Connection/blob/master/webapp/pages/profile/_id/_slug.vue#L20)

### Steps to reproduce the behavior
1.Seed database 
2. Go to http://localhost:3000/profile/u5/trick
3. Click on the content menu and report user
4. See the bug

### Expected behavior
Only one error message telling me: "Thank you for reporting this user"

### Additional context
@Tirokk @mattwr18 @ulfgebhardt @ogerly @appinteractive 
This is a nice example why I find it a design problem to use mixins. Use mixins **only** as a last resort to remove redundancy. Mixins are *hard* to maintain. They have surprising, unexpected behaviour and they create errors.

@Tirokk could you have a look if there is a clean way how to refactor the code and not use a mixin? The test of the profile page [here](https://github.com/Human-Connection/Human-Connection/blob/master/webapp/pages/profile/_id/_slug.spec.js#L56) is a false negative. It's green but it shouldn't be green. The problem is that you're mocking `this.post`. The page component does not have a property `this.post` at all. It had `this.User` and it will have `this.Post` in the future (which is an array of records not a single record) but it clearly does not have `this.post`. So in the test, you're testing the mocked behaviour by manually invoking the callback. To avoid this in the future, you could prefer to click on sth. That is less error-prone than using `wrapper.vm`.

**Comment by Tirokk** [comment]
Hey @roschaefer ,

I will not say, that everything went correct here. You got a point!
This callback is probably never been called here. And it is seemingly at the wrong place.

Please let us pair on it at Wednesday, because I am at quitting my work and have to go fore now.
And I will usually not be really viable before Wednesday. On Tuesday I have Yoga and in the afternoon I drive to my fathers place.
If it is really important for you, lets pair tomorrow, okay.
Please write me on Zoom, what you like to do.

**Comment by ogerly** [comment]
ERROR: A user should only be reported once per user. otherwise it looks like this :| 

![FireShot Capture 140 - Human Connection - Human Connection - localhost](https://user-images.githubusercontent.com/1324583/59378885-a581e200-8d55-11e9-8a7f-f523aa2acda4.png)

TODO in : https://github.com/Human-Connection/Human-Connection/pull/803

**Comment by ogerly** [comment]
here is the workflow: https://github.com/Human-Connection/Human-Connection/pull/803

**Comment by Tirokk** [comment]
Solved by #811
