### ISSUE TITLE
🐛 [Bug] full ads width use with small devices

### ISSUE THREAD

**Issue by ogerly** [Human-Connection/Human-Connection#957]
## :bug: Bugreport
with small devices, the maximum width should be used for the content. 
the cards and pictures should be responsive

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/1324583/60567819-7b777a80-9d6b-11e9-8bce-c3faf96fbd54.gif)

### Steps to reproduce the behavior
1. look at the page on small end devices, on small devices it tears up the design.
 

### Expected behavior
for small devices, the full width should be used for the display. minimal edges for the pretty and ok.
with small devices, the full width should be used for the display. minimal margins for the pretty and ok. from a fixed size, the width of the css is adjusted to 100 %. 

### Version & Environment
 Type: []       [Smartphone]

**Comment by mattwr18** [comment]
I just had a look on `nitro-production` and I wasn't able to replicate this bug
I think you are getting this because you are manually adjusting the width instead of choosing a device
I just chose all the devices available in the dev tools on chromium, and there is no issue.
I think you are choosing breakpoints that don't exist on real devices?

**Comment by roschaefer** [comment]
@mattwr18 @ogerly I'm trying to reproduce the bug and the fix in #958. I think the layout is messed up for one-column displays, because we have this small blue ribbon on the top right corner of the post, saying "post". I can reproduce a strangely squeezed post card in Firefox in a narrow one-column layout.
